Feature/autostake length
Axion-Network/axion-contracts pull request #66
Opened 2020-12-29 04:54 UTC by JTravaux

Please review this carefully and let me know if anything needs to be changed. Autostake length can be from 14 - 5555 days and will fail if its not within those numbers.

2020-12-29 05:21 UTC, imkrish commented on contracts/Auction.sol
> +        uint256 stakeDays;
Unfortunately, we are using upgradable contracts we cannot update the existing state variable. (struct)

2020-12-29 06:09 UTC, Dellybro requested changes

2020-12-29 06:09 UTC, Dellybro commented on contracts/Auction.sol
> +    mapping(uint256 => mapping(address => uint256)) public autoStakeDaysOf;
no this needs to be the LAST variable

2020-12-29 06:21 UTC, JTravaux commented on contracts/Auction.sol
> +    mapping(uint256 => mapping(address => uint256)) public autoStakeDaysOf;
ok

2020-12-29 08:01 UTC, imkrish commented on test/upgradeability/upgradeability.ts
> +      expect(autoStakeDaysAfter.toString()).to.eq(
AWESOME bro!

2020-12-29 08:18 UTC, JTravaux commented on contracts/Auction.sol
> +            stakeDays = autoStakeDaysOf[auctionId][_msgSender()];
Will think of how to test this in the morning (its 3am!), since I'm unable to set a stake with a stakeDays as 0.

2020-12-29 08:25 UTC, sigurdpl commented on contracts/Auction.sol
> +        require(stakeDays >= options.autoStakeDays, "stakeDays < 14 days");
hmm, just cosmetical, but min stakedays is not 14 days anymore. Its 60days

2020-12-29 08:57 UTC, imkrish commented on contracts/Auction.sol
> +            stakeDays = autoStakeDaysOf[auctionId][_msgSender()];
Thanks a lot for your work bro. Love it.

I think we can use upgradeProxy for this:

1. Deploy the old auction contract (before this change) (Let's create the new file and put it in contracts/archives/Auction29122012.sol)
2. Place the bid
3. Upgrade auction contract (to this new one)
4. Withdraw

2020-12-29 08:57 UTC, imkrish commented on contracts/Auction.sol
> +            stakeDays = autoStakeDaysOf[auctionId][_msgSender()];
And please go to sleep first :smile:

2020-12-29 18:34 UTC, JTravaux commented on contracts/Auction.sol
> +            stakeDays = autoStakeDaysOf[auctionId][_msgSender()];
So I committed another update with the test you mentioned above. However I ran into an error when trying to 'withdraw' from the auction. **VM Exception while processing transaction: revert Caller is not a minter**

Tried some stuff to try to solve it, including setting up some roles for account1, with no success.

2020-12-29 18:51 UTC, JTravaux commented
@imkrish Also, any idea why the coverage check is reporting mostly 0's locally when I add 'archives' to the .solcover.js skipFiles array? 

- with 'archives' included
![image](https://user-images.githubusercontent.com/30296275/103306861-99fc1780-49dc-11eb-8599-af688eb4acaf.png)

- without 'archives' included
![image](https://user-images.githubusercontent.com/30296275/103306872-a2545280-49dc-11eb-8cbc-6f2491af28fc.png)

2020-12-29 19:39 UTC, JTravaux commented
Do we keep referral autoStakeDays at 14, or change it to options.autoStakeDays which is currently 60?

![image](https://user-images.githubusercontent.com/30296275/103309598-830cf380-49e3-11eb-8227-aeffa1270a89.png)

2020-12-29 21:49 UTC, imkrish commented on contracts/Auction.sol
> +            stakeDays = autoStakeDaysOf[auctionId][_msgSender()];
I have fixed it

2020-12-29 21:57 UTC, imkrish approved these changes

2020-12-30 04:38 UTC, Dellybro approved these changes

2020-12-30 04:38 UTC, merged